package model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Dathang generated by hbm2java
 */
@Entity
@Table(name = "dathang", catalog = "mypham")
public class Dathang implements java.io.Serializable {

	private DathangId id;

	public Dathang() {
	}

	public Dathang(DathangId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tenKhach", column = @Column(name = "TenKhach", nullable = false, length = 150)),
			@AttributeOverride(name = "diaChi", column = @Column(name = "DiaChi", nullable = false, length = 300)),
			@AttributeOverride(name = "sdt", column = @Column(name = "SDT", nullable = false, length = 11)),
			@AttributeOverride(name = "maKv", column = @Column(name = "MaKV", nullable = false, length = 3)),
			@AttributeOverride(name = "maSp", column = @Column(name = "MaSP", nullable = false, length = 4)),
			@AttributeOverride(name = "soLuong", column = @Column(name = "SoLuong", nullable = false)),
			@AttributeOverride(name = "ngayDat", column = @Column(name = "NgayDat", nullable = false, length = 19)) })
	public DathangId getId() {
		return this.id;
	}

	public void setId(DathangId id) {
		this.id = id;
	}

}
