package model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Khuvuc generated by hbm2java
 */
@Entity
@Table(name = "khuvuc", catalog = "mypham")
public class Khuvuc implements java.io.Serializable {

	private String maKv;
	private String tenKv;
	private double phiGiaoHang;

	public Khuvuc() {
	}

	public Khuvuc(String maKv, String tenKv, double phiGiaoHang) {
		this.maKv = maKv;
		this.tenKv = tenKv;
		this.phiGiaoHang = phiGiaoHang;
	}

	@Id

	@Column(name = "MaKV", unique = true, nullable = false, length = 3)
	public String getMaKv() {
		return this.maKv;
	}

	public void setMaKv(String maKv) {
		this.maKv = maKv;
	}

	@Column(name = "TenKV", nullable = false, length = 200)
	public String getTenKv() {
		return this.tenKv;
	}

	public void setTenKv(String tenKv) {
		this.tenKv = tenKv;
	}

	@Column(name = "PhiGiaoHang", nullable = false, precision = 22, scale = 0)
	public double getPhiGiaoHang() {
		return this.phiGiaoHang;
	}

	public void setPhiGiaoHang(double phiGiaoHang) {
		this.phiGiaoHang = phiGiaoHang;
	}

}
