package model;
// default package
// Generated Feb 5, 2018 8:45:13 PM by Hibernate Tools 5.1.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name = "district", catalog = "mypham")
public class RstDistrictDto implements java.io.Serializable {

	private String districtId;
	private String name;
	private String provinceId;

	public RstDistrictDto() {
	}

	public RstDistrictDto(String districtId, String name) {
		this.districtId = districtId;
		this.name = name;
	}

	public RstDistrictDto(String districtId) {
		this.districtId = districtId;
	}

	@Id

	@Column(name = "DistrictID", unique = true, nullable = false, length = 4)
	public String getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(String districtId) {
		this.districtId = districtId;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ProvinceID", nullable = false, length = 4)
	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

}
