package model;
// default package
// Generated Feb 4, 2018 3:01:45 PM by Hibernate Tools 5.1.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "mypham")
public class RstOrderDto implements java.io.Serializable {

	private Integer orderId;
	private String deliveryAdress;
	private double totalPrice;
	private Date orderDate;
	private Date deliveryDate;
	private RstProvinceDto provinceDto;
	private RstDistrictDto districtDto;
	private RstVillageDto villageDto;
	private boolean state;
	private RstCustomerDto customerDto;
	private Set<RstOrderDetailDto> orderDetailDtos;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OrderID", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "DeliveryAdress", nullable = false, length = 80)
	public String getDeliveryAdress() {
		return this.deliveryAdress;
	}

	public void setDeliveryAdress(String deliveryAdress) {
		this.deliveryAdress = deliveryAdress;
	}

	@Column(name = "TotalPrice", nullable = false, precision = 22, scale = 0)
	public double getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(double totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OrderDate", nullable = false, length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DeliveryProvinceID", referencedColumnName = "ProvinceID")
	public RstProvinceDto getProvinceDto() {
		return provinceDto;
	}

	public void setProvinceDto(RstProvinceDto provinceDto) {
		this.provinceDto = provinceDto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DeliveryDistrictID", referencedColumnName = "DistrictID", nullable = false)
	public RstDistrictDto getDistrictDto() {
		return districtDto;
	}

	public void setDistrictDto(RstDistrictDto districtDto) {
		this.districtDto = districtDto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DeliveryVillageID", referencedColumnName = "ID", nullable = false)
	public RstVillageDto getVillageDto() {
		return villageDto;
	}

	public void setVillageDto(RstVillageDto villageDto) {
		this.villageDto = villageDto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DeliveryDate", length = 19)
	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	@Column(name = "State", nullable = false)
	public boolean getState() {
		return this.state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerID")
	public RstCustomerDto getCustomerDto() {
		return customerDto;
	}

	public void setCustomerDto(RstCustomerDto customerDto) {
		this.customerDto = customerDto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderDto", cascade = CascadeType.PERSIST)
	public Set<RstOrderDetailDto> getOrderDetailDtos() {
		return orderDetailDtos;
	}

	public void setOrderDetailDtos(Set<RstOrderDetailDto> orderDetailDtos) {
		this.orderDetailDtos = orderDetailDtos;
	}

}
