package model;
// default package
// Generated Feb 4, 2018 3:01:45 PM by Hibernate Tools 5.1.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "order_detail", catalog = "mypham")
public class RstOrderDetailDto implements java.io.Serializable {

	private Integer id;
	private int maSp;
	private double gia;
	private int soLuong;
	private double thanhTien;
	private RstOrderDto orderDto;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "MaSP", nullable = false)
	public int getMaSp() {
		return this.maSp;
	}

	public void setMaSp(int maSp) {
		this.maSp = maSp;
	}

	@Column(name = "Gia", nullable = false, precision = 22, scale = 0)
	public double getGia() {
		return this.gia;
	}

	public void setGia(double gia) {
		this.gia = gia;
	}

	@Column(name = "SoLuong", nullable = false)
	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "ThanhTien", nullable = false, precision = 22, scale = 0)
	public double getThanhTien() {
		return this.soLuong * this.gia;
	}

	public void setThanhTien(double thanhTien) {
		this.thanhTien = thanhTien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OrderID", nullable = false)
	public RstOrderDto getOrderDto() {
		return orderDto;
	}

	public void setOrderDto(RstOrderDto orderDto) {
		this.orderDto = orderDto;
	}

}
