package model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loaisanpham generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_TYPE", catalog = "mypham")
public class RstProducTypeDto implements java.io.Serializable {

	private static final long serialVersionUID = 7868929283582140257L;
	private String maLoai;
	private String tenLoai;
	private Integer stt;
	private Set<RstProductDto> rstProductDtos = new HashSet<RstProductDto>();

	@Id
	@Column(name = "MaLoai", unique = true, nullable = false, length = 20)
	public String getMaLoai() {
		return this.maLoai;
	}

	public void setMaLoai(String maLoai) {
		this.maLoai = maLoai;
	}

	@Column(name = "TenLoai", nullable = false, length = 200)
	public String getTenLoai() {
		return this.tenLoai;
	}

	public void setTenLoai(String tenLoai) {
		this.tenLoai = tenLoai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rstProducTypeDto")
	public Set<RstProductDto> getRstProductDtos() {
		return rstProductDtos;
	}

	public void setRstProductDtos(Set<RstProductDto> rstProductDtos) {
		this.rstProductDtos = rstProductDtos;
	}

	@Column(name = "STT")
	public Integer getStt() {
		return stt;
	}

	public void setStt(Integer stt) {
		this.stt = stt;
	}

}
