package model;
// default package
// Generated Feb 5, 2018 8:45:13 PM by Hibernate Tools 5.1.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Province generated by hbm2java
 */
@Entity
@Table(name = "province", catalog = "mypham")
public class RstProvinceDto implements java.io.Serializable {

	private String provinceId;
	private String name;

	public RstProvinceDto() {
	}

	public RstProvinceDto(String provinceId) {
		this.provinceId = provinceId;
	}

	@Id

	@Column(name = "ProvinceID", unique = true, nullable = false, length = 3)
	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
