package model;
// default package
// Generated Feb 5, 2018 8:45:13 PM by Hibernate Tools 5.1.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Village generated by hbm2java
 */
@Entity
@Table(name = "village", catalog = "mypham")
public class RstVillageDto implements java.io.Serializable {

	private String id;
	private String name;
	private String districtId;

	public RstVillageDto() {
	}

	public RstVillageDto(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public RstVillageDto(String id) {
		this.id = id;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 4)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DistrictID", nullable = false, length = 4)
	public String getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(String districtId) {
		this.districtId = districtId;
	}

}
